### ISSUE TITLE
Teargas line issue still persists

### ISSUE THREAD

**Issue by ghost** [HugoZink/PD2_VocalHeisters#2]
This occurred when I got burned by the Thermite in FWB. I tried to record it, but I screwed up the recording.

Also, I might be wrong, but this doesn't occur on _smaller_ _Thermites._; e.g. The Thermite from the Big Bank Heist.

**Comment by morerokk** [comment]
The first world bank thermite is programmed to act like a large teargas zone. Therefore, I literally cannot fix this on FWB. I've got it fixed everywhere else though. Sorry!
